import { motion } from "framer-motion"

const data = [
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores saepe tempora eius fugiat accusantium quia, iste ad in adipisci sed asperiores esse ratione harum atque ea velit! Nemo dolorum animi eligendi, provident eius culpa? Fuga, debitis ratione nobis dolorum tenetur a voluptate illum odit libero, voluptatum voluptas error, magnam dolores praesentium modi! Blanditiis, autem ipsa explicabo ut quia corporis voluptatem, recusandae sit dicta dolorum nulla nam quo vero eligendi nihil voluptates voluptate nemo quibusdam molestiae, hic soluta odio dignissimos dolor.",
]

const ScrollStaggered = () => {
    return (
        <div>
            <div style={{ maxWidth: 1200, marginInline: 'auto', }}>
                <motion.ul style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: '10px' }}>
                    {
                        data.map((value, index) => (
                            <motion.li initial={{ opacity: 0, y: 100 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: (index % 4) / 10 }} style={{ padding: '1rem', borderRadius: 5, border: '1px solid rgba(0 0 0/.4)', width: 280 }} viewport={{ once: true }} key={index}>
                                {value}
                            </motion.li>
                        ))
                    }
                </motion.ul>
            </div>
        </div>
    )
}

export default ScrollStaggered